### ISSUE TITLE
Dual-Core instead of Quad-Core?

### ISSUE THREAD

**Issue by lucasgabmoreno** [RidhaAF/Hackintosh-ASUS-A455LB#1]
Hi!
I was trying to use OpenCore in my MEDION Akoya E6418 MD99620 (CX 22953 in Argentina) with no luck until your guide.
Your EFI works! Thanks!!!!

(It has same architecture: Core i5 Broadwell + Nvidia 940M)

**But I've the same problem I saw in your image:
It says Dual-Core instead of Quad-Core.**

Did you experiment less perfomance?

<img src="https://raw.githubusercontent.com/RidhaAF/Hackintosh-Asus-A455LB/master/img/Screen%20Shot%202020-11-29%20at%207.58.01%20AM.png">

**Comment by RidhaAF** [comment]
Core i5-5200U does have 2 cores and 4 threads, so I think it's right.
